# 배열 생성

## 리스트로 배열 만들기

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.22.4'

In [ ]:
# 1차원 array

a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))

print(a1.shape) # 차원 출력

print(a1[0], a1[1]) # index로 접근가능

a1[0] = 100 # array 값 변경 가능
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2
[100   2   3   4   5]


In [ ]:
# 2차원 array

a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a2)
print(a2.shape) #차원출력 (3,3) 열방향 : axis0, 행방향 : axis1

print(a2[0,0], a2[1,1], a2[2,2]) #index 접근
print(a2[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9
6


In [ ]:
#3차원 array

a3 = np.array([[ [1,2], [4,5], [7,8] ],
               [ [1,2], [4,5], [7,8] ],
               [ [1,2], [4,5], [7,8] ],
               [ [1,2], [4,5], [7,8] ]])
print(a3)
print(a3.shape) # 차원 : axis3

[[[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]]
(4, 3, 2)


## 배열 생성 및 초기화

In [ ]:
# 모든 요소가 0인 배열을 생성

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# 모든 요소가 1인 배열을 생성

np.ones((3,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# 지정한 값으로 배열을 생성

np.full((3,3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [ ]:
# 단위행렬(항등행렬) 생성

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 삼각행렬(아래삼각행렬) 생상

np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [ ]:
# 초기화되지 않은 배열 생성(기존 메모리위치에 존재하는 값을 불러온다)

np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 지정된 배열과 shape가 같은 배열 생성

print(a1)
np.zeros_like(a1)

[100   2   3   4   5]


array([0, 0, 0, 0, 0])

In [ ]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
print(a3)
np.full_like(a3, 3)

[[[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]]


array([[[3, 3],
        [3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3],
        [3, 3]]])

## 생성한 값으로 배열 생성

In [ ]:
# arange(start, end, step) : 정수 범위로 배열생성

np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
# linspace(start, end, size) : 범위 내에서 균등 간격의 배열 생성

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# logspace() : 범위 내에서 균등 간격으로 로그 스케일로 배열 생성

np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

## 램덤값(난수)으로 배열 생성  

|함수|설명|
|-|-|
|seed|난수 발생을 위한(seed) 생성|
|permutation|순서를 임의로 바꾸거나 임의의 정수 순열 반환|
|shuffle|리스트나 배열의 순서를 뒤섞음(inplace)|
|binomial|이항분포에서 표본 추출|
|uniform|균등(a,b)분포에서 표본추출|



In [ ]:
# random.random() : 랜덤한 수의 배열 생성(0~1)

np.random.random((3,3))

array([[0.09126894, 0.3286607 , 0.89317425],
       [0.43676188, 0.70423388, 0.87325545],
       [0.19474851, 0.27942884, 0.39615442]])

In [ ]:
# random.randint(min, max, size) : 일정 구간(min ~ max-1)의 랜덤 정수의 배열 생성

np.random.randint(0,10, ((3,3)))

array([[1, 3, 3],
       [4, 4, 2],
       [1, 7, 2]])

In [ ]:
# random.normal(mean, std, size) : 정규분포

np.random.normal(0,1, size = (3,3))

array([[ 0.65818188, -0.29142204, -0.41249443],
       [-1.33453308, -0.24843007,  1.64181288],
       [ 0.40542606,  0.5561849 , -0.17075883]])

In [ ]:
# random.rand() : 균등분포(0,1)

np.random.rand(3,3)

array([[0.74063224, 0.3928145 , 0.92282844],
       [0.98032257, 0.96699117, 0.51956874],
       [0.94887496, 0.31677644, 0.62146485]])

In [ ]:
# random.randn() : 표준 정규분포

np.random.randn(3,3)

array([[-1.5022922 ,  0.58596436,  0.83316532],
       [-1.49499443, -0.38280396,  0.87672645],
       [-1.61561695, -2.80808959, -0.43213777]])

In [ ]:
# random.binomial(n,p, size) : 이항분포 , n = 시행횟수, p = 확률, size = 전체 실험 횟수

np.random.binomial(10, 1/6, 10) # 주사위의 눈이 6이 나오면 성공인 이항분포, 주사위를 10번던지는 행위를 10번반복

array([2, 1, 2, 2, 1, 1, 1, 1, 1, 1])

## 표준데이터 타입[링크 텍스트]

|데이터 타입|설명|
|-|-|
|bool|바이트로 저장된 boolean으로 True 또는 False값을가짐|
|int|기본 정수(integer)타입
|intc|C 언어에서 사용되는 int와 동일|
|int8|바이트 (-128 ~ 127), [int16, int32, int64도 있다]|
|uint8|부호 없는 정수 (0 ~ 255), [uint16, uint32, uint64도 있다]|

In [ ]:
np.zeros(20, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3,3), 1.0, dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 날짜/시간 배열 생성



In [ ]:
#날짜를 계산가능한 형태로 변경

date = np.array('2020-01-01', dtype = np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [ ]:
#날짜를 array 형태로 더해줄 수 있다.

date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [ ]:
datetime = np.array('2020-06-01 12:00', dtype = np.datetime64)
datetime

array('2020-06-01T12:00', dtype='datetime64[m]')

In [ ]:
# 바로 날짜 형태로 만들 수 있다.

print(np.datetime64('2020-06-01 12:00', 'm') + np.arange(12))
print(np.datetime64('2020-06-01 12:00' , 'h') + np.arange(12))

['2020-06-01T12:00' '2020-06-01T12:01' '2020-06-01T12:02'
 '2020-06-01T12:03' '2020-06-01T12:04' '2020-06-01T12:05'
 '2020-06-01T12:06' '2020-06-01T12:07' '2020-06-01T12:08'
 '2020-06-01T12:09' '2020-06-01T12:10' '2020-06-01T12:11']
['2020-06-01T12' '2020-06-01T13' '2020-06-01T14' '2020-06-01T15'
 '2020-06-01T16' '2020-06-01T17' '2020-06-01T18' '2020-06-01T19'
 '2020-06-01T20' '2020-06-01T21' '2020-06-01T22' '2020-06-01T23']


# 배열조회

## 배열 속성 정보

In [ ]:
def array_info(array):
  print(array)
  print("ndim: ", array.ndim)
  print("shape: ", array.shape)
  print('dtype: ', array.dtype)
  print('size: ', array.size)
  print('itemsize: ', array.itemsize) #하나의 itemsize(int : 8byte)
  print('nbytes: ', array.nbytes) # size * itemsize
  print('strides: ', array.strides)

In [ ]:
array_info(a1)

[100   2   3   4   5]
ndim:  1
shape:  (5,)
dtype:  int64
size:  5
itemsize:  8
nbytes:  40
strides:  (8,)


In [ ]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim:  2
shape:  (3, 3)
dtype:  int64
size:  9
itemsize:  8
nbytes:  72
strides:  (24, 8)


In [ ]:
array_info(a3)

[[[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]]
ndim:  3
shape:  (4, 3, 2)
dtype:  int64
size:  24
itemsize:  8
nbytes:  192
strides:  (48, 16, 8)


## 인덱싱(Indexing)

In [ ]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[100   2   3   4   5]
100
3
5
4


In [ ]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [ ]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,1,1])
print(a3[2,-1,-1])

[[[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]]
1
5
5
8


## 슬라이싱


*   슬라이싱 구문 : a[strart:stop:step]
*   기본값 : start=0, stop=size-1, step=1



In [ ]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[100   2   3   4   5]
[100   2]
[100   2   3   4   5]
[100]
[100   3   5]
[  5   4   3   2 100]


In [ ]:
print(a2, '\n')
print(a2[1],'\n')
print(a2[1,:],'\n')
print(a2[:2,:2],'\n')
print(a2[1:,::-1],'\n')
print(a2[::-1,::-1],'\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[4 5 6] 

[4 5 6] 

[[1 2]
 [4 5]] 

[[6 5 4]
 [9 8 7]] 

[[9 8 7]
 [6 5 4]
 [3 2 1]] 



## 불리언 인덱싱

In [ ]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])

[100   2   3   4   5]
[2 3 5]


In [ ]:
print(a2)
bi = np.random.randint(0,2, (3,3), dtype = bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False  True]]
[6 7 9]


## 팬시 인덱싱

In [ ]:
print(a1)
print(a1[0], a1[2])
idx = [0,2]
print(a1[idx])
# print(a1[0,2]) 오류 print(a1[[0,2]]) 가능
ind = np.array([[0,1],
                [2,0]])
print(a1[ind])

[100   2   3   4   5]
100 3
[100   3]
[[100   2]
 [  3 100]]


In [ ]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


# 배열 값 삽입/수정/삭제/복사

## 배열 값 삽입
* insert(array, 위치, 값) : 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)

[100   2   3   4   5]
[ 10 100   2   3   4   5]


In [ ]:
print(a2)
b2 = np.insert(a2, 1, 10, axis = 0)
print(b2)
c2 = np.insert(a2, 1, 10, axis = 1)
print(c2)
d2 = np.insert(a2, 1,10)
print(d2) #axis를 지정하지 않으면 1차원 배열로 변환

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[ 1  0  1]
 [10 10 10]
 [ 4  2  0]
 [ 7  8  9]]
[[ 1 10  0  1]
 [ 4 10  2  0]
 [ 7 10  8  9]]
[ 1 10  0  1  4  2  0  7  8  9]


## 배열 값 수정
*  배열의 인덱싱으로 접근하여 값 수정

In [ ]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1,3,4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[9 2 3 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [ ]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
a2[2,2] = 3
print(a2)
a2[0] = 1
print(a2)
a2[1:, 2] = 9
print(a2)

row = np.array([0,1])
col = np.array([1,2])
a2[row, col] = 0
print(a2)

[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 1 1]
 [4 2 9]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


## 배열 값 삭제
* delete() : 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환
* inplace X

In [ ]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [ ]:
print(a2)
b2 = np.delete(a2, 1, axis = 0)
print(b2)
c2 = np.delete(a2, 1, axis = 1)
print(c2)
d2 = np.delete(a2, 1)
print(d2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]
[1 1 4 2 0 7 8 9]


## 배열 복사
* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님
* 복사가 필요하면 copy() 사용

In [ ]:
a2 = np.array([[1,0,1],[4,2,0],[7,8,9]])
print(a2)
print(a2[:2,:2])
a2_sub = a2[:2,:2]
print(a2_sub)
a2_sub[:,1] = 0
print(a2_sub)
print(a2) #a2_sub를 바꿨는데 원본 a2도 바뀐다

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


In [ ]:
print(a2)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 10
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[ 1 10]
 [ 4 10]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


# 배열 변환

## 배열 전치 및 축 변경

In [ ]:
print(a2)
print(a2.T) # transpose

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [ ]:
print(a3)
print(a3.T)

[[[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]]
[[[1 1 1 1]
  [4 4 4 4]
  [7 7 7 7]]

 [[2 2 2 2]
  [5 5 5 5]
  [8 8 8 8]]]


In [ ]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [ ]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]]
[[[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[4 5]
  [4 5]
  [4 5]
  [4 5]]

 [[7 8]
  [7 8]
  [7 8]
  [7 8]]]
[[[1 4 7]
  [2 5 8]]

 [[1 4 7]
  [2 5 8]]

 [[1 4 7]
  [2 5 8]]

 [[1 4 7]
  [2 5 8]]]


## 배열 재구조화
* reshape() : 배열의 형상을 변경

In [ ]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape((3,3)))
print(n1) #원본 배열이 변경되지 않는다

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


* newaxis() : 새로운 축 추가

In [ ]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


## 배열 크기 변경

* 배열 모양만 변경

In [ ]:
n2 = np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2)) #아무것도 출력되지않는다
print(n2) #원본이 바뀐다

[[6 4 7 3 5]
 [1 6 7 3 7]]
[[6 4]
 [7 3]
 [5 1]
 [6 7]
 [3 7]]


* 배열 크기 증가시 남은 공간은 0으로 채워짐 (현재 numpy버전에서는 안됨)




In [ ]:
n2.resize((5,5), refcheck = False) #refcheck = False 가 없으면 오류
print(n2)

[[6 4 7 3 5]
 [1 6 7 3 7]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
n2.resize((3,3), refcheck = False) #refcheck = False 가 없으면 오류
print(n2)

[[6 4 7]
 [3 5 1]
 [6 7 3]]


## 배열 추가
* np.append() : 배열의 끝에 값 추가
* array에서는 append 메소드를 사용할 수 없다.
* np.append(a,b) 가능, a.append(b) 불가능



In [ ]:
import numpy as np

a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변환되어 결합

In [ ]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* 열 shape 이 맞아야한다

In [ ]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* 행 shape이 맞아야한다

In [ ]:
c2 = np.append(a2,b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


## 배열 연결
* concatenate([array1, array2, array3...]) : 튜플이나 배열의 리스트를 인수로 사용해 배열 연결
* np.append는 2개이하 배열 결합, np.concatenate는 여러 배열 결합 가능

In [ ]:
a1 = np.arange(1,7,2)
b1 = np.arange(2,8,2)
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [ ]:
c1 = np.arange(7,10)
np.concatenate([a1,b1,c1])

TypeError: ignored

In [ ]:
a2 = np.arange(1,7).reshape(2,3)
np.concatenate([a2,a2]) #default axis = 0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2 = np.arange(1,7).reshape(2,3)
np.concatenate([a2,a2], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* vstack() : 수직 스택, 1차원으로 연결

In [ ]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* hstack() : 수평스택, 2차원으로 연결

In [ ]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* dstack() : 깊이 스택, 3차원으로 연결

In [ ]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* stack() : 새로운 차원으로 연결

In [ ]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

## 배열 분할

In [ ]:
# split() : 배열 분할

a1 = np.arange(0,10)
print(a1)
b1, c1 = np.split(a1,[5])
print(b1,c1)

b1, c1, d1, e1, f1 = np.split(a1, [2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


In [ ]:
# vsplit() : 수직분할

a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.vsplit(a2, [2])
print(b2); print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [ ]:
# hsplit() : 수평분할

a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.hsplit(a2, [2])
print(b2); print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [ ]:
# dsplit() : 깊이분할

a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.dsplit(a3,[2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


# 배열 연산
* NumPy의 배열 연산은 벡터화(vectoried) 연산을 사용
* 일반적으루 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행


## 브로드캐스팅
* shape(행방향 or 열방향)이 동일해야 한다

In [ ]:
a1 = np.arange(1,4)
print(a1)
print(a1 + 1, '\n') # [1,2,3] + 5 error

a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1 + a2, '\n')

b2 = np.arange(1,4).reshape(3,1)
print(b2)
print(a1 + b2)

[1 2 3]
[2 3 4] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]] 

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 산술 연산

In [ ]:
# np.add, np.subtract

a1 = np.arange(1,10)
print(a1)
print(a1 + 1)
print(np.add(a1, 10)) # not np.sum()
print(a1-2)
print(np.subtract(a1,10))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]


In [ ]:
# np.negative

print(-a1)
print(np.negative(a1))

[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]


In [ ]:
# np.multiply, np.divide, np.floor_divide

print(a1 * 3)
print(np.multiply(a1, 3), '\n')

print(a1 / 2)
print(np.divide(a1,2), '\n')

print(a1 // 2)
print(np.floor_divide(a1,2)) #round_divide, celing_divide 는 없다

[ 3  6  9 12 15 18 21 24 27]
[ 3  6  9 12 15 18 21 24 27] 

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5] 

[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]


In [ ]:
# np.power, np.mod

print(a1 ** 2)
print(np.power(a1, 2), '\n')

print(a1 % 2)
print(np.mod(a1,2))

[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81] 

[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [ ]:
#배열의 shape이 맞다면 서로다른 배열에대해 연산이 가능하다.

a1 = np.arange(1,10)
print(a1)

np.random.seed(3)
b1 = np.random.randint(1,10, size = 18).reshape(2,9)
print(b1,'\n')

print(np.add(a1,b1),'\n')
print(np.subtract(a1,b1),'\n')
print(np.multiply(a1,b1),'\n')
print(np.divide(a1,b1),'\n')
print(np.floor_divide(a1,b1),'\n')
print(np.power(a1,b1),'\n')
print(np.mod(a1,b1),'\n')

[1 2 3 4 5 6 7 8 9]
[[9 4 9 9 1 6 4 6 8]
 [7 1 5 8 9 2 7 3 3]] 

[[10  6 12 13  6 12 11 14 17]
 [ 8  3  8 12 14  8 14 11 12]] 

[[-8 -2 -6 -5  4  0  3  2  1]
 [-6  1 -2 -4 -4  4  0  5  6]] 

[[ 9  8 27 36  5 36 28 48 72]
 [ 7  2 15 32 45 12 49 24 27]] 

[[0.11111111 0.5        0.33333333 0.44444444 5.         1.
  1.75       1.33333333 1.125     ]
 [0.14285714 2.         0.6        0.5        0.55555556 3.
  1.         2.66666667 3.        ]] 

[[0 0 0 0 5 1 1 1 1]
 [0 2 0 0 0 3 1 2 3]] 

[[       1       16    19683   262144        5    46656     2401   262144
  43046721]
 [       1        2      243    65536  1953125       36   823543      512
       729]] 

[[1 2 3 4 0 0 3 2 1]
 [1 0 3 4 5 0 0 2 0]] 



## 절대값 함수

In [ ]:
# absolute(), abs(): 내장된 절대값함수

a1 = np.random.randint(-10,10, size = 5)

print(a1)
print(np.absolute(a1))
print(abs(a1))

[-9  9 -5 -2  4]
[9 9 5 2 4]
[9 9 5 2 4]


## 제곱/제곱근 함수

In [ ]:
print(a1)
print(np.square(a1))
print(np.sqrt(abs(a1)))

[-9  9 -5 -2  4]
[81 81 25  4 16]
[3.         3.         2.23606798 1.41421356 2.        ]


## 지수와 로그 함수

In [ ]:
a1 = np.random.randint(1,10,size = 5)
print(a1)
print(np.exp(a1)) # e**a1
print(np.exp2(a1)) # 2**a1
print(np.power(a1,2)) # a1**2

[2 9 8 9 2]
[7.38905610e+00 8.10308393e+03 2.98095799e+03 8.10308393e+03
 7.38905610e+00]
[  4. 512. 256. 512.   4.]
[ 4 81 64 81  4]


In [ ]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))
np.log()

[2 9 8 9 2]
[0.69314718 2.19722458 2.07944154 2.19722458 0.69314718]
[1.       3.169925 3.       3.169925 1.      ]
[0.30103    0.95424251 0.90308999 0.95424251 0.30103   ]


## 삼각함수

In [ ]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


## 집계함수

In [ ]:
# sum() : 모든 원소의 합 계산

np.random.seed(4)
a2 = np.random.randint(1,10, size=(2, 3, 5))
print(a2)
print(a2.sum())
print(a2.sum(axis = 0))
print('')
print(a2.sum(axis = 1))
print('')
print(a2.sum(axis = 2))
#print(np.sum(a2), np.sum(a2, axis = 0), np.sum(a2, axis = 1), np.sum(a2, axis=2))

[[[8 6 2 9 8]
  [9 3 8 8 8]
  [9 5 3 7 5]]

 [[4 1 8 6 6]
  [7 7 9 3 6]
  [9 2 3 8 1]]]
178
[[12  7 10 15 14]
 [16 10 17 11 14]
 [18  7  6 15  6]]

[[26 14 13 24 21]
 [20 10 20 17 13]]

[[33 36 29]
 [25 32 23]]


In [ ]:
a2 = np.random.randint(1,10, size=(2, 3, 5, 4))
a2

array([[[[6, 6, 2, 9],
         [8, 6, 1, 4],
         [1, 7, 7, 7],
         [3, 9, 8, 9],
         [1, 4, 9, 2]],

        [[8, 9, 3, 8],
         [1, 1, 6, 8],
         [3, 2, 8, 1],
         [6, 1, 8, 6],
         [1, 3, 7, 2]],

        [[9, 9, 5, 2],
         [2, 3, 5, 4],
         [8, 2, 3, 5],
         [6, 5, 5, 6],
         [9, 2, 2, 5]]],


       [[[9, 2, 5, 5],
         [8, 2, 5, 3],
         [7, 8, 4, 8],
         [5, 5, 9, 9],
         [7, 3, 6, 1]],

        [[1, 6, 6, 7],
         [8, 3, 3, 4],
         [2, 5, 8, 8],
         [3, 6, 5, 3],
         [7, 1, 2, 3]],

        [[7, 7, 7, 6],
         [7, 2, 6, 6],
         [5, 4, 5, 1],
         [6, 7, 2, 9],
         [6, 1, 6, 3]]]])

In [ ]:
# cumsum() : 누적합 계산

print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis = 0))
print(np.cumsum(a2, axis = 1))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
[ 1  7 12 14 20 25 33 40 41]
[[ 1  6  5]
 [ 3 12 10]
 [11 19 11]]
[[ 1  7 12]
 [ 2  8 13]
 [ 8 15 16]]


In [ ]:
# diff() : 차분 계산

print(a2)
print(np.diff(a2))
print(np.diff(a2, axis = 0))
print(np.diff(a2, axis = 1))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
[[ 5 -1]
 [ 4 -1]
 [-1 -6]]
[[ 1  0  0]
 [ 6  1 -4]]
[[ 5 -1]
 [ 4 -1]
 [-1 -6]]


In [ ]:
# prod(): 모든 원소의 곱의 합 계산

print(a2)
print(np.prod(a2))
print(np.prod(a2, axis = 0))
print(np.prod(a2, axis = 1))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
100800
[ 16 252  25]
[30 60 56]


In [ ]:
# cumprod(): 누적곱 계산

print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis = 0))
print(np.cumprod(a2, axis = 1))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
[     1      6     30     60    360   1800  14400 100800 100800]
[[  1   6   5]
 [  2  36  25]
 [ 16 252  25]]
[[ 1  6 30]
 [ 2 12 60]
 [ 8 56 56]]


In [ ]:
# dot()/matmul() : 행렬곱 계산

print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2,b2))
print(np.matmul(a2,b2))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[12 12 12]
 [13 13 13]
 [16 16 16]]
[[12 12 12]
 [13 13 13]
 [16 16 16]]


In [ ]:
# tensordot() : 텐서 곱 계산

print(a2)
print(b2)
print(np.tensordot(a2,b2))
print(np.tensordot(a2, b2, axes = 0))
print(np.tensordot(a2, b2, axes = 1))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
41
[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]


 [[[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]]
[[12 12 12]
 [13 13 13]
 [16 16 16]]


In [ ]:
# cross(): 벡터곱

x = [1,2,3]
y = [4,5,6]

print(np.cross(x,y))

[-3  6 -3]


In [ ]:
# inner()/outer(): 내적 외적

print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[12 12 12]
 [13 13 13]
 [16 16 16]]
[[1 1 1 1 1 1 1 1 1]
 [6 6 6 6 6 6 6 6 6]
 [5 5 5 5 5 5 5 5 5]
 [2 2 2 2 2 2 2 2 2]
 [6 6 6 6 6 6 6 6 6]
 [5 5 5 5 5 5 5 5 5]
 [8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 7 7]
 [1 1 1 1 1 1 1 1 1]]


In [ ]:
# mean() : 평균 계산

print(a2)
print(np.mean(a2))
print(np.mean(a2, axis = 0))
print(np.mean(a2, axis = 1))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
4.555555555555555
[3.66666667 6.33333333 3.66666667]
[4.         4.33333333 5.33333333]


In [ ]:
# var(),std() : 분산, 표준편차 계산

print(a2)
print(np.var(a2), np.var(a2, axis = 0), np.var(a2, axis = 1))
print(np.std(a2), np.std(a2, axis = 0), np.std(a2, axis = 1))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
6.024691358024692 [9.55555556 0.22222222 3.55555556] [4.66666667 2.88888889 9.55555556]
2.454524670486058 [3.09120617 0.47140452 1.88561808] [2.1602469  1.69967317 3.09120617]


In [ ]:
# min(), max() : 최소값, 최대값 계산

print(a2)
print(np.min(a2), np.min(a2, axis = 0), np.min(a2, axis = 1))
print(np.max(a2), np.max(a2, axis = 0), np.max(a2, axis = 1))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
1 [1 6 1] [1 2 1]
8 [8 7 5] [6 6 8]


In [ ]:
# argmin(), argmax() : 최소값 인덱스, 최대값 인덱스

print(a2)
print(np.argmin(a2), np.argmin(a2, axis = 0), np.argmin(a2, axis = 1))
print(np.argmax(a2), np.argmax(a2, axis = 0), np.argmax(a2, axis = 1))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
0 [0 0 2] [0 0 2]
6 [2 2 0] [1 1 0]


In [ ]:
# median() : 중앙값

print(a2)
print(np.median(a2))
print(np.median(a2, axis = 0))
print(np.median(a2, axis = 1))

[[1 6 5]
 [2 6 5]
 [8 7 1]]
5.0
[2. 6. 5.]
[5. 5. 7.]


In [ ]:
# percentile() : 백분위수

a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1, [0,20,40,60,80,100], interpolation = 'linear'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation = 'higher'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation = 'lower'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation = 'nearest'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation = 'midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


In [ ]:
# any() : True가 1개 이상있으면 True반환

a2 = np.random.randint(0,2,size = 9, dtype = bool).reshape(3,3)
print(a2)
print(np.any(a2))
print(np.any(a2, axis = 0))
print(np.any(a2, axis = 1))

[[False  True False]
 [False  True False]
 [False False  True]]
True
[False  True  True]
[ True  True  True]


In [ ]:
# all() : 모든 원소가 True면 True 반환

a2 = np.random.randint(0,2,size = 9, dtype = bool).reshape(3,3)
print(a2)
print(np.all(a2))
print(np.all(a2, axis = 0))
print(np.all(a2, axis = 1))

[[False False  True]
 [False  True  True]
 [ True False  True]]
False
[False False  True]
[False False False]


## 비교연산

In [ ]:
a1 = np.arange(1,10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 > 5)
print(a1 >= 5)
print(a1 < 5)
print(a1 <= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]


In [ ]:
a2 = a1.reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2>5))
print(np.sum(a2>5))
print(np.sum(a2>5, axis = 0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]


In [ ]:
# isclose() : 배열의 원소들 간 가까우면 True

a1 = np.array([1,2,3,4,5])
b1 = np.array([1,2,3,3,4])

print(np.isclose(a1,b1))

[ True  True  True False False]


In [ ]:
# isinf() : inf값 확인

a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))


[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


# 배열 정렬

In [ ]:
a1 = np.random.randint(1,10,size = 10)
print(a1)
print(np.sort(a1))
print(a1) #정렬 반열 x
print(np.argsort(a1))
print(a1[np.argsort(a1)])
a1.sort() #정렬 반열 o
print(a1)

[1 6 1 2 5 2 3 3 5 9]
[1 1 2 2 3 3 5 5 6 9]
[1 6 1 2 5 2 3 3 5 9]
[0 2 3 5 6 7 4 8 1 9]
[1 1 2 2 3 3 5 5 6 9]
[1 1 2 2 3 3 5 5 6 9]


In [ ]:
a2 = np.random.randint(1,10, size = (3,3))
print(a2)
print(np.sort(a2, axis = 0))
print(np.sort(a2, axis = 1))

[[1 7 1]
 [5 2 6]
 [2 9 9]]
[[1 2 1]
 [2 7 6]
 [5 9 9]]
[[1 1 7]
 [2 5 6]
 [2 9 9]]


## 부분정렬

In [ ]:
# parttion() : 배열에서 k개의 작은 값을 반환

a1 = np.random.randint(1,10, size = 10)
print(a1)
print(np.partition(a1,3)) #제일 작은값 3개를 앞으로 반환

[8 1 1 2 8 9 8 5 1 1]
[1 1 1 1 2 5 8 8 9 8]


In [ ]:
a2 = np.random.randint(1,10, size = (4,4))
print(a2)
print(np.partition(a2, 2, axis = 0))
print(np.partition(a2, 2, axis = 1))

[[7 8 2 1]
 [1 6 9 5]
 [9 9 4 5]
 [3 6 5 8]]
[[1 6 2 1]
 [3 6 4 5]
 [7 8 5 5]
 [9 9 9 8]]
[[1 2 7 8]
 [1 5 6 9]
 [4 5 9 9]
 [3 5 6 8]]


# 배열 입출력

In [ ]:
# np.save() 배열객체 1개를 파일에 저장

a2 = np.random.randint(1,10, size = (5,5))
print(a2)
np.save("a", a2)

[[2 1 8 5 9]
 [9 5 2 5 1]
 [6 7 8 1 8]
 [9 2 6 4 7]
 [2 4 8 5 1]]


In [ ]:
!ls #현제 directory 파일에 저장된 파일 불러오기

a.npy  sample_data


In [ ]:
# np.savez() 여러 배열객체를 파일에 저장

b2 = np.random.randint(1,10, size = (5,5))
print(b2)
np.savez('ab',a2,b2)

[[9 5 8 9 6]
 [7 8 4 6 2]
 [9 3 9 5 6]
 [1 9 8 2 3]
 [6 3 8 7 8]]


In [ ]:
!ls

ab.npz	a.npy  sample_data


In [ ]:
# numpy 객체 불러오기

npy = np.load('a.npy')
print(npy)

[[2 1 8 5 9]
 [9 5 2 5 1]
 [6 7 8 1 8]
 [9 2 6 4 7]
 [2 4 8 5 1]]


In [ ]:
npz = np.load('ab.npz')
print(npz) #주소값이 나온다
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[2 1 8 5 9]
 [9 5 2 5 1]
 [6 7 8 1 8]
 [9 2 6 4 7]
 [2 4 8 5 1]]
[[9 5 8 9 6]
 [7 8 4 6 2]
 [9 3 9 5 6]
 [1 9 8 2 3]
 [6 3 8 7 8]]


In [ ]:
# numpy 객체를 text로 저장

print(a2)
np.savetxt('a.csv', a2, delimiter = ',') # comma separate values : csv

[[2 1 8 5 9]
 [9 5 2 5 1]
 [6 7 8 1 8]
 [9 2 6 4 7]
 [2 4 8 5 1]]


In [ ]:
!cat a.csv

2.000000000000000000e+00 1.000000000000000000e+00 8.000000000000000000e+00 5.000000000000000000e+00 9.000000000000000000e+00
9.000000000000000000e+00 5.000000000000000000e+00 2.000000000000000000e+00 5.000000000000000000e+00 1.000000000000000000e+00
6.000000000000000000e+00 7.000000000000000000e+00 8.000000000000000000e+00 1.000000000000000000e+00 8.000000000000000000e+00
9.000000000000000000e+00 2.000000000000000000e+00 6.000000000000000000e+00 4.000000000000000000e+00 7.000000000000000000e+00
2.000000000000000000e+00 4.000000000000000000e+00 8.000000000000000000e+00 5.000000000000000000e+00 1.000000000000000000e+00


In [ ]:
# savetxt 개체를 불러오기

csv = np.loadtxt('a.csv', delimiter = ',')
print(csv)

[[2. 1. 8. 5. 9.]
 [9. 5. 2. 5. 1.]
 [6. 7. 8. 1. 8.]
 [9. 2. 6. 4. 7.]
 [2. 4. 8. 5. 1.]]


In [ ]:
# save할때 소수점 갯수 조정

print(b2)
np.savetxt('b2.csv', b2, delimiter = ',', fmt = '%.2e', header = 'c1, c2, c3, c4, c5')

[[9 5 8 9 6]
 [7 8 4 6 2]
 [9 3 9 5 6]
 [1 9 8 2 3]
 [6 3 8 7 8]]


In [ ]:
csv = np.loadtxt('b2.csv', delimiter = ',')
print(csv)

[[9. 5. 8. 9. 6.]
 [7. 8. 4. 6. 2.]
 [9. 3. 9. 5. 6.]
 [1. 9. 8. 2. 3.]
 [6. 3. 8. 7. 8.]]
